version: '3.8'

services:
  db:
    build: .
    container_name: modernrepo_postgres
    environment:
      POSTGRES_DB: postgres_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "3002:3002"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-p", "3002"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: modernrepo_adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    depends_on:
      - db

volumes:
  postgres_data:
