# Spring DATASOURCE for test profile
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres-db}:${DB_PORT:3020}/${DB_NAME:modernrepo}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
